SMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500, handler400
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('app.urls')),
    path('accounts/', include('accounts.urls')),
    path('programs/', include('course.urls')),
    path('result/', include('result.urls')),
    path('search/', include('search.urls')),
    path('quiz/', include('quiz.urls')),
    path('payments/', include('payments.urls')),


    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'app.views.handler404'
# handler500 = 'app.views.handler500'
# handler400 = 'app.views.handler400'

course/urls.py
from django.urls import path
from .views import *

# from . import views

urlpatterns = [
    # Program urls
    path('', program_view, name='programs'),
    path('<int:pk>/detail/', program_detail, name='program_detail'),
    path('add/', program_add, name='add_program'),
    path('<int:pk>/edit/', program_edit, name='edit_program'),
    path('<int:pk>/delete/', program_delete, name='program_delete'),

    # Course urls
    path('course/<slug>/detail/', course_single, name='course_detail'),
    path('<int:pk>/course/add/', course_add, name='course_add'),
    path('courses/add/', add_course, name='add_course'),

    path('course/<slug>/edit/', course_edit, name='edit_course'),
    path('course/delete/<slug>/', course_delete, name='delete_course'),

    # CourseAllocation urls
    path('course/assign/', CourseAllocationFormView.as_view(), name='course_allocation'),
    path('course/allocated/', course_allocation_view, name='course_allocation_view'),
    path('allocated_course/<int:pk>/edit/', edit_allocated_course, name='edit_allocated_course'),
    path('course/<int:pk>/deallocate/', deallocate_course, name='course_deallocate'),
    #    path('payment/', views.payment, name='payment'),

    # File uploads urls
    path('course/<slug>/documentations/upload/', handle_file_upload, name='upload_file_view'),
    path('course/<slug>/documentations/<int:file_id>/edit/', handle_file_edit, name='upload_file_edit'),
    path('course/<slug>/documentations/<int:file_id>/delete/', handle_file_delete, name='upload_file_delete'),

    # Video uploads urls
    path('course/<slug>/video_tutorials/upload/', handle_video_upload, name='upload_video'),
    path('course/<slug>/video_tutorials/<video_slug>/detail/', handle_video_single, name='video_single'),
    path('course/<slug>/video_tutorials/<video_slug>/edit/', handle_video_edit, name='upload_video_edit'),
    path('course/<slug>/video_tutorials/<video_slug>/delete/', handle_video_delete, name='upload_video_delete'),

    # course registration
    path('course/registration', course_registration, name='course_registration'),
    path('course/drop/', course_drop, name='course_drop'),

    path('my_courses/', user_course_list, name="user_course_list"),
]

course/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.core.validators import FileExtensionValidator
from django.db.models.signals import pre_save
from django.db.models import Q
# project import
from .utils import *


ONE ='ONE'
TWO = 'TWO'
THREE ='THREE'
FOUR ='FOUR'
FIVE ='FIVE'
SIX ='SIX'

YEARS = (
        (ONE, 'ONE'),
        (TWO, 'TWO'),
        (THREE, 'THREE'),
        (FOUR, 'FOUR'),
        (FIVE, 'FIVE'),
        (SIX, 'SIX'),
    )

# LEVEL_COURSE = "Level course"
CREECH = "Creech"
NURSERY = "Nusery"
BASIC = "Basic"

LEVEL = (
    # (LEVEL_COURSE, "Level course"),
    (CREECH, "Creech"),
    (NURSERY, "Nusery Certificate"),
    (BASIC,  "Basic Certificate")
)


FIRST = "First"
SECOND = "Second"
THIRD = "Third"

SEMESTER = (
    (FIRST, "First"),
    (SECOND, "Second"),
    (THIRD, "Third"),
)



class ProgramManager(models.Manager):
    def search(self, query=None):
        qs = self.get_queryset()
        if query is not None:
            or_lookup = (Q(title__icontains=query) | 
                         Q(summary__icontains=query)
                        )
            qs = qs.filter(or_lookup).distinct() # distinct() is often necessary with Q lookups
        return qs


class Program(models.Model):
    title = models.CharField(max_length=150, unique=True)
    summary = models.TextField(null=True, blank=True)

    objects = ProgramManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('program_detail', kwargs={'pk': self.pk})


class CourseManager(models.Manager):
    def search(self, query=None):
        qs = self.get_queryset()
        if query is not None:
            or_lookup = (Q(title__icontains=query) | 
                         Q(summary__icontains=query)| 
                         Q(code__icontains=query)| 
                         Q(slug__icontains=query)
                        )
            qs = qs.filter(or_lookup).distinct() # distinct() is often necessary with Q lookups
        return qs


class Course(models.Model):
    slug = models.SlugField(blank=True, unique=True)
    title = models.CharField(max_length=200, null=True)
    code = models.CharField(max_length=200, unique=True, null=True)
    credit = models.IntegerField(null=True, default=0)
    summary = models.TextField(max_length=200, blank=True, null=True)
    program = models.ForeignKey(Program, on_delete=models.CASCADE)
    level = models.CharField(max_length=25, choices=LEVEL, null=True)
    year = models.CharField(choices=YEARS, max_length=20, default='')
    semester = models.CharField(choices=SEMESTER, max_length=20)
    is_elective = models.BooleanField(default=False, blank=True, null=True)

    objects = CourseManager()

    def __str__(self):
        return "{0} ({1})".format(self.title, self.code)

    def get_absolute_url(self):
        return reverse('course_detail', kwargs={'slug': self.slug})
    
    @property
    def is_current_semester(self):
        from app.models import Semester
        current_semester = Semester.objects.get(is_current_semester=True)

        if self.semester == current_semester.semester:
            return True
        else:
            return False


def course_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(course_pre_save_receiver, sender=Course)


class CourseAllocation(models.Model):
    lecturer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='allocated_lecturer')
    courses = models.ManyToManyField(Course, related_name='allocated_course')
    session = models.ForeignKey("app.Session", on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.lecturer.get_full_name

    def get_absolute_url(self):
        return reverse('edit_allocated_course', kwargs={'pk': self.pk})


class Upload(models.Model):
    title = models.CharField(max_length=100)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    file = models.FileField(upload_to='course_files/', validators=[FileExtensionValidator(['pdf', 'docx', 'doc', 'xls', 'xlsx', 'ppt', 'pptx', 'zip', 'rar', '7zip'])])
    updated_date = models.DateTimeField(auto_now=True, auto_now_add=False, null=True)
    upload_time = models.DateTimeField(auto_now=False, auto_now_add=True, null=True)

    def __str__(self):
        return str(self.file)[6:]

    def get_extension_short(self):
        ext = str(self.file).split(".")
        ext = ext[len(ext)-1]

        if ext == 'doc' or ext == 'docx':
            return 'word'
        elif ext == 'pdf':
            return 'pdf'
        elif ext == 'xls' or ext == 'xlsx':
            return 'excel'
        elif ext == 'ppt' or ext == 'pptx':
            return 'powerpoint'
        elif ext == 'zip' or ext == 'rar' or ext == '7zip':
            return 'archive'

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)


class UploadVideo(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(blank=True, unique=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    video = models.FileField(upload_to='course_videos/', validators=[FileExtensionValidator(['mp4', 'mkv', 'wmv', '3gp', 'f4v', 'avi', 'mp3'])])
    summary = models.TextField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True, null=True)

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        return reverse('video_single', kwargs={'slug': self.course.slug, 'video_slug': self.slug})

    def delete(self, *args, **kwargs):
        self.video.delete()
        super().delete(*args, **kwargs)


def video_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(video_pre_save_receiver, sender=UploadVideo)


class CourseOffer(models.Model):
	dep_head = models.ForeignKey("accounts.DepartmentHead", on_delete=models.CASCADE)
	def __str__(self):
		return "{}".format(self.dep_head)

course/forms.py
from django.contrib.auth.models import User
from django import forms

from accounts.models import User
from .models import Program, Course, CourseAllocation, Upload, UploadVideo, LEVEL, YEARS

# User = settings.AUTH_USER_MODEL

class ProgramForm(forms.ModelForm):
    class Meta:
        model = Program
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control'})
        self.fields['summary'].widget.attrs.update({'class': 'form-control'})


class CourseAddForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control'})
        self.fields['code'].widget.attrs.update({'class': 'form-control'})
        self.fields['courseUnit'].widget.attrs.update({'class': 'form-control'})
        self.fields['credit'].widget.attrs.update({'class': 'form-control'})
        self.fields['summary'].widget.attrs.update({'class': 'form-control'})
        self.fields['program'].widget.attrs.update({'class': 'form-control'})
        self.fields['level'].widget.attrs.update({'class': 'form-control'})
        self.fields['year'].widget.attrs.update({'class': 'form-control'})
        self.fields['semester'].widget.attrs.update({'class': 'form-control'})


class CourseAllocationForm(forms.ModelForm):
    courses = forms.ModelMultipleChoiceField(
        queryset=Course.objects.all().order_by('level'),
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'browser-default checkbox'}),
        required=True
    )
    lecturer = forms.ModelChoiceField(
        queryset=User.objects.filter(is_lecturer=True),
        widget=forms.Select(attrs={'class': 'browser-default custom-select'}),
        label="lecturer",
    )

    class Meta:
        model = CourseAllocation
        fields = ['lecturer', 'courses']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(CourseAllocationForm, self).__init__(*args, **kwargs)
        self.fields['lecturer'].queryset = User.objects.filter(is_lecturer=True)


class EditCourseAllocationForm(forms.ModelForm):
    courses = forms.ModelMultipleChoiceField(
        queryset=Course.objects.all().order_by('level'),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )
    lecturer = forms.ModelChoiceField(
        queryset=User.objects.filter(is_lecturer=True),
        widget=forms.Select(attrs={'class': 'browser-default custom-select'}),
        label="lecturer",
    )

    class Meta:
        model = CourseAllocation
        fields = ['lecturer', 'courses']

    def __init__(self, *args, **kwargs):
        #    user = kwargs.pop('user')
        super(EditCourseAllocationForm, self).__init__(*args, **kwargs)
        self.fields['lecturer'].queryset = User.objects.filter(is_lecturer=True)


# Upload files to specific course
class UploadFormFile(forms.ModelForm):
    class Meta:
        model = Upload
        fields = ('title', 'file', 'course',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control'})
        self.fields['file'].widget.attrs.update({'class': 'form-control'})


# Upload video to specific course
class UploadFormVideo(forms.ModelForm):
    class Meta:
        model = UploadVideo
        fields = ('title', 'video', 'course',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control'})
        self.fields['video'].widget.attrs.update({'class': 'form-control'})

class CourseFilterForm(forms.Form):
    level = forms.ChoiceField(choices=LEVEL, label='Level', required=False)
    session = forms.ChoiceField(choices=YEARS, label='Session', required=False)


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'

templates/course/add_course.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div id="input-nav">
    <a href="{% url 'home' %}" class="primary1">Home</a> <i>&rsaquo;</i>
    <a href="{% url 'programs' %}" class="primary1">Programs</a> <i>&rsaquo;</i> Add & Update Subject
</div>

<div class="title-1">Subject Add & Update Form</div>
<div class="title-line"></div>


<form action="" method="POST" class="mt-4">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <p class="form-title">Subject Info</p>
                <div class="p-3">
                    <div class="form-group">
                        <label for="id_title"><b>SUBJECT:</b></label>
                        {{ form.title }}
                        <span class="danger">{{ form.title.errors }}</span>
                        <p class="text-muted-xs">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</p>
                    </div>
                    <div class="form-group">
                        <label for="id_code"><b>Code:</b></label>
                        {{ form.code }}
                        <span class="danger">{{ form.code.errors }}</span>
                        <p class="text-muted-xs">The Subject code must be similar to only the pre requests.</p>
                    </div>
                    <div class="form-group">
                        <label for="id_summary"><b>Summary:</b></label>
                        {{ form.summary }}
                        <span class="danger">{{ form.summary.errors }}</span>
                        <p class="text-muted-xs">Enter some description about the Subject.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <p class="form-title">Applicant Info</p>
                <div class="p-3">
                    <div class="form-group">
                        <label for="id_program"><b>Program:</b></label>
                        {{ form.program }}
                        <span class="danger">{{ form.program.errors }}</span>
                    </div>
                    <div class="form-group">
                        <label for="id_credit"><b>Credit:</b></label>
                        {{ form.credit }}
                        <span class="danger">{{ form.credit.errors }}</span>
                    </div>
                    <div class="form-group">
                        <label for="id_year"><b>Year:</b></label>
                        {{ form.year }}
                        <span class="danger">{{ form.year.errors }}</span>
                    </div>
                    <div class="form-group">
                        <label for="id_semester"><b>Semester:</b></label>
                        {{ form.semester }}
                        <span class="danger">{{ form.semester.errors }}</span>
                    </div>
                    <div class="form-group">
                        <label for="id_level"><b>Level:</b></label>
                        {{ form.level }}
                        <span class="danger">{{ form.level.errors }}</span>
                    </div>
                    <div class="form-group">
                        <label for="id_is_elective"><b>Is Elective:</b></label>
                        {{ form.is_elective }}
                        <span class="danger">{{ form.is_elective.errors }}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <center><input class="btn btn-outline-primary mt-3" type="submit" value="ADD COURSE"></center>
</form>

{% endblock content %}

templates/course/bursary.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>School Bursary Receipt</title>

</head>
<body>
    <div id="input-nav" class="p-2">
        <a href="{% url 'home' %}"> Home </a> Bursary
    </div>

<div class="table-responsive table-shadow table-light table-striped m-0 mt-5">

    <div id="receipt">
        <div id="receipt-header">
            <h1>School Bursary Receipt</h1>
        </div>

        <div id="school-info">
            <p><strong>School Name:</strong> XYZ School</p>
            <p><strong>School Address:</strong> 123 School Street, City</p>
        </div>

        <div id="student-info">
            <p><strong>Student Name:</strong> John Doe</p>
            <p><strong>Grade/Class:</strong> 10th Grade</p>
        </div>

        <table id="items-table">
            <thead>
                <tr>
                    <th>Description</th>
                    <th>Quantity</th>
                    <th>Unit Price</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Tuition Fee Bursary</td>
                    <td>1</td>
                    <td>$500.00</td>
                    <td>$500.00</td>
                </tr>
            </tbody>
        </table>

        <div id="total">
            <p><strong>Total Amount:</strong> $500.00</p>
        </div>
    </div>
        <div id="footer">
            <p>Thank you for your support!</p>
        </div>
    </div>
</body>

{% endblock content %}

templates/course/course_add.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div id="input-nav"><a href="{% url 'home' %}" class="primary1">Home</a> <i>&rsaquo;</i> 
    <a href="{% url 'programs' %}" class="primary1">Programs</a> <i>&rsaquo;</i> Add & Update Subject</div>

<div class="title-1">Subject Add & Update Form</div>
<div class="title-line"></div>


<form action="" method="POST">{% csrf_token %}
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <p class="form-title">Subject Info</p>
                <div class="p-3">

                    <div class="form-group">
                        <b>{{ form.title.label }}</b>{{ form.title }}
                        <span class="danger">{{ form.title.errors }}</span>
                        <p class="text-muted-xs">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</p>
                    </div>
                    <div class="form-group">
                        <b>{{ form.code.label }}</b>{{ form.code }}
                        <span class="danger">{{ form.code.errors }}</span>
                        <p class="text-muted-xs">The Subject code must be similar to only the pre requests.</p>
                    </div>
                    <div class="form-group">
                        <b>{{ form.summary.label }}</b>(optional){{ form.summary }}
                        <span class="danger">{{ form.summary.errors }}</span>
                        <p class="text-muted-xs">Enter some description about the Subject.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <p class="form-title">Applicant Info</p>
                <div class="p-3">
                    
                    <div class="form-group">
                        <b>{{ form.program.label }}</b>{{ form.program }}
                        <span class="danger">{{ form.program.errors }}</span>
                    </div>
                    <div class="form-group">
                        <b>{{ form.credit.label }}</b>{{ form.credit }}
                        <span class="danger">{{ form.credit.errors }}</span>
                    </div>
                    <div class="form-group">
                        <b>{{ form.year.label }}</b>{{ form.year }}
                        <span class="danger">{{ form.year.errors }}</span>
                    </div>
                    <div class="form-group">
                        <b>{{ form.semester.label }}</b>{{ form.semester }}
                        <span class="danger">{{ form.semester.errors }}</span>
                    </div>
                    <div class="form-group">
                        <b>{{ form.level.label }}</b>{{ form.level }}
                        <span class="danger">{{ form.level.errors }}</span>
                    </div>
                    <div class="form-group">
                        <b>{{ form.is_elective.label }}</b>{{ form.is_elective }}
                        <span class="danger">{{ form.is_elective.errors }}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <center><input class="btn btn-outline-primary mt-3" type="submit" value="ADD COURSE"></center>
</form>

{% endblock content %}

templates/course/course_allocation_form.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div id="input-nav"><a href="{% url 'home' %}" class="primary1">Home</a> <i>&rsaquo;</i> 
    <a href="{% url 'course_allocation_view' %}" class="primary1">Allocations</a> <i>&rsaquo;</i> Add</div>
<br>


<div class="row">
    <div class="col-md-6 mx-auto">
        <div class="card">
            <p class="form-title">Subject Allocation Form</p>
            <div class="p-3">
                <form action="" method="POST">{% csrf_token %}
                        <div class="form-group">
                            {{ form.lecturer.label }}{{ form.lecturer }}
                            <span class="danger">{{ form.lecturer.errors }}</span>
                        </div>
                        <div class="form-group">
                            {{ form.courses.label }}{{ form.courses }}
                            <span class="danger">{{ form.courses.errors }}</span>
                        </div>
                        
                    {% for course in form.courses.all %}{{ course }}{% endfor %}

                    <input class="btn btn-outline-primary" type="submit" value="Save">
                </form>
            </div>
        </div>

    </div>
</div>

{% endblock content %}

templates/course/message.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% load static %}

{% block content %}

<div class="container3">
    <div id="input-nav" class="p-2"><a href="{% url 'home' %}"> Home </a> Message Notifications</div>


    <h1>Inbox</h1>

        <ul>
        </ul>
          {% for message in received_messages %}
            <li>
                {% if message.is_read %}
                    <a href="{% url 'open_message' message.id %}">
                        <p class="notification-number">{{ forloop.counter }}</p>
                        📨 | {{ message.title }}<br>
                        <ol>{{ message.content|slice:":50"}}................<br ><<< See More >>> </ol>
                        <br> <ol>{{ message.created_at }}</ol>
                    </a>
            <hr>______________________________________________________________________

                {% else %}
                    <strong>
                        <a href="{% url 'open_message' message.id %}">
                            <p class="notification-number">{{ forloop.counter }}*</p>
                         (*New ✉) | {{ message.title }} <br> <ol>{{ message.content|slice:":20"}}................
                            <br><<< See More >>><br></ol>
                            <small>{{ message.created_at }}</small>
                        </a>
                    </strong>
                    <hr>______________________________________________________________________

                {% endif %}
            </li>
        {% endfor %}
    </ul>
            <p>Total Received Messages: {{ received_messages.count }}</p>

</div>
{% endblock content %}

templates/course/program_add.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div id="input-nav"><a href="{% url 'home' %}" class="primary1">Home</a> <i>&rsaquo;</i> 
    <a href="{% url 'programs' %}" class="primary1">Programs</a> <i>&rsaquo;</i> Add</div>
<br>


<div class="row">
<div class="col-md-6 mx-auto">
    <div class="card">
        <p class="form-title">Program Add Form</p>
        <div class="p-3"><br>
            <form action="" method="POST">{% csrf_token %}

                <div class="form-group">
                    <b>{{ form.title.label }}</b>{{ form.title }}
                    <span class="danger">{{ form.title.errors }}</span>
                </div>
                <div class="form-group">
                    <b>{{ form.summary.label }}</b>{{ form.summary }}
                    <span class="danger">{{ form.summary.errors }}</span>
                </div>

                <input class="btn btn-outline-primary" type="submit" value="Save">
            </form>
        </div>
    </div>
</div>
</div>
{% endblock content %}

templates/course/program_list.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}

{% block content %}
<div id="input-nav"><a href="{% url 'home' %}" class="primary1">Home</a> <i>&rsaquo;</i> Programs</div>

{% if request.user.is_superuser %}
<a class="add-button" href="{% url 'add_program' %}"><i class="fas fa-plus"></i>Add Program</a>
{% endif %}

<div class="title-1"><i class="fas fa-book-open"></i>Program List</div>
<div class="title-line"></div>

<div class="content-center">
    <form class="search-form mx-auto" action="" method="GET">{% csrf_token %}
        <input class="au-input" type="text" name="program_filter" placeholder="Program name"
            value="{{ request.GET.program_filter }}" />
        <button class="btn btn-light" type="submit">
            <i class="fas fa-search"></i> Filter
        </button>
    </form>
</div>

<!-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Launch demo modal
</button> -->

<!-- Modal -->
{% for program in programs %}
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <p class="p-4">
                Are you sure you want to delete this item?
            </p>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a class="btn btn-danger" href="{% url 'program_delete' pk=program.pk %}">Delete</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}


<div class="table-responsive table-shadow table-light table-striped m-0 mt-5">
    <div class="table-shadow">
        <table class="table table-light">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Program Name</th>
                    <th>Summary</th>
                    {% if request.user.is_superuser %}
                    <th>Action</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for program in programs %}
                <tr>
                    <td>{{ forloop.counter }}.</td>
                    <td><a class="a-list">
                        <!-- href="{{ program.get_absolute_url }}"> -->
                            {{ program.title}}</a></td>
                    <td>{{ program.summary }} </td>
                    {% if request.user.is_superuser %}

                    <td>
                        <div class="update-delete">
                            <a href="{% url 'edit_program' pk=program.pk %}" class="update"><i
                                    class="fas fa-edit"></i></a>
                            <button type="button" class="btn btn-sm" data-toggle="modal" data-target="#exampleModal">
                                <i class="fas fa-trash-alt"></i>
                            </button>
                        </div>

                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                            aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <p class="p-4">
                                        Are you sure you want to delete this program?
                                    </p>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary"
                                            data-dismiss="modal">Close</button>
                                        <a class="btn btn-danger"
                                            href="{% url 'program_delete' pk=program.pk %}">Delete</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- <td> <div class="update-delete">
                    <a href="{% url 'edit_program' pk=program.pk %}" class="update"><i class="fas fa-edit"></i></a> 
                    <a href="{% url 'program_delete' pk=program.pk %}" class="delete"><i class="fas fa-trash-alt"></i></a>
                    </div> -->
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}