SMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500, handler400
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('app.urls')),
    path('accounts/', include('accounts.urls')),
    path('programs/', include('course.urls')),
    path('result/', include('result.urls')),
    path('search/', include('search.urls')),
    path('quiz/', include('quiz.urls')),
    path('payments/', include('payments.urls')),


    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'app.views.handler404'
# handler500 = 'app.views.handler500'
# handler400 = 'app.views.handler400'

accounts/urls.py
from django.urls import path, include
from django.contrib.auth.views import (
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, 
    PasswordResetCompleteView, LoginView, LogoutView
    )
from . import views

from .views import (
        profile, profile_single, admin_panel,view_messages, open_message, assemble_payment,
        profile_update, change_password, create_message,
        LecturerListView, StudentListView,
        staff_add_view, edit_staff,
        delete_staff, student_add_view,
        edit_student, delete_student, ParentAdd, validate_username, register
    )
from .forms import EmailValidationOnForgotPassword
from .views import parentview

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('messages/create/', create_message.as_view(), name='create_message'),

    path('admin_panel/', admin_panel, name='admin_panel'),
    path('generate-pdf/', views.generate_pdf, name='generate_pdf'),

    path('profile/', profile, name='profile'),
    path('profile/<int:id>/detail/', profile_single, name='profile_single'),
    path('setting/', profile_update, name='edit_profile'),
    path('change_password/', change_password, name='change_password'),

    path('lecturers/', LecturerListView.as_view(), name='lecturer_list'),
    path('lecturer/add/', staff_add_view, name='add_lecturer'),
    path('staff/<int:pk>/edit/', edit_staff, name='staff_edit'),
    path('lecturers/<int:pk>/delete/', delete_staff, name='lecturer_delete'),

    path('students/', StudentListView.as_view(), name='student_list'),
    path('student/add/', student_add_view, name='add_student'),
    path('student/<int:pk>/edit/', edit_student, name='student_edit'),
    path('students/<int:pk>/delete/', delete_student, name='student_delete'),

    path('parents/add/', ParentAdd, name='add_parent'),
    path('view/', parentview, name='view_parent'),
    path('view_messages/', view_messages, name='view_messages'),

    path('ajax/validate-username/', validate_username, name='validate_username'),
    path('message/<int:message_id>/', open_message, name='open_message'),

    path('register/', register, name='register'),

    # path('add-student/', StudentAddView.as_view(), name='add_student'),

    # path('programs/course/delete/<int:pk>/', course_delete, name='delete_course'),

    # Setting urls
    # path('profile/<int:pk>/edit/', profileUpdateView, name='edit_profile'),
    # path('profile/<int:pk>/change-password/', changePasswordView, name='change_password'),

    # ################################################################
    # path('login/', LoginView.as_view(), name='login'),
    # path('logout/', LogoutView.as_view(), name='logout', kwargs={'next_page': '/'}),
    path('assemble-payment/', assemble_payment, name='assemble_payment'),
    path('password-reset/', PasswordResetView.as_view(
         form_class=EmailValidationOnForgotPassword,
         template_name='password_reset_form.html'
     ),
          name='reset'),

     path('password-reset/done/', PasswordResetDoneView.as_view(
         template_name='registration/password_reset_done.html'
     ),
          name='password_reset_done'),
     path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
         template_name='registration/password_reset_confirm.html'
     ),
          name='password_reset_confirm'),
     path('password-reset-complete/', PasswordResetCompleteView.as_view(
         template_name='registration/password_reset_complete.html'
     ),
          name='password_reset_complete')
    # ################################################################
]

accounts/models.py
from course.models import Program
from django.db import models
from django.urls import reverse
from django.conf import settings
import random
from datetime import datetime
from django.db.models import Q
from PIL import Image
from django.utils import timezone
from .validators import ASCIIUsernameValidator
from django.contrib.auth.models import AbstractUser, UserManager



FATHER = "Father"
MOTHER = "Mother"
BROTHER = "Brother"
SISTER = "Sister"
GRAND_MOTHER = "Grand mother"
GRAND_FATHER = "Grand father"
OTHER = "Other"

RELATION_SHIP  = (
    (FATHER, "Father"),
    (MOTHER, "Mother"),
    (BROTHER, "Brother"),
    (SISTER, "Sister"),
    (GRAND_MOTHER, "Grand mother"),
    (GRAND_FATHER, "Grand father"),
    (OTHER, "Other"),
)


BUS_SERVICE_CHOICES = [
    ('yes', 'Yes'),
    ('no', 'No'),
    ('not_now', 'Not Now'),
]

BUS_SERVICE_TYPE_CHOICES = [
    ('both-ways', 'Both Ways'),
    ('one-way', 'One-way'),
    ('not_now', 'Not Now'),

]

PICKUP_OR_DROPOFF_CHOICES = [
    ('pickup', 'Pickup'),
    ('dropoff', 'Dropoff'),
    ('not_now', 'Not Now'),

]

CHOICES = [
    ('yes', 'Yes'),
    ('no', 'No'),
    ('not_now', 'Not Now'),
]

ONE ='ONE'
TWO = 'TWO'
THREE ='THREE'
FOUR ='FOUR'
FIVE ='FIVE'
SIX ='SIX'

YEARS = (
        ('', '--'),  # Add an empty choice with "--" as value and label
        (ONE, 'ONE'),
        (TWO, 'TWO'),
        (THREE, 'THREE'),
        (FOUR, 'FOUR'),
        (FIVE, 'FIVE'),
        (SIX, 'SIX'),
    )

FIRST = "First"
SECOND = "Second"
THIRD = "Third"

SEMESTER = (
    ('', '--'),  # Add an empty choice with "--" as value and label
    (FIRST, "First"),
    (SECOND, "Second"),
    (THIRD, "Third"),
)

# LEVEL_COURSE = "Level course"
CREECH = "Creech"
NURSERY = "Nusery"
BASIC = "Basic"

LEVEL = (
    ('', '--'),  # Add an empty choice with "--" as value and label
    (CREECH, "Creech"),
    (NURSERY, "Nusery Certificate"),
    (BASIC,  "Basic Certificate")
)

PAYMENT_CHOICES = (
    ('', '--'),  # Add an empty choice with "--" as value and label
    ('PENDING  ❌', 'Pending'),
    ('APPROVED ✔', 'Approved'),
    ('ADVANCED 🕛', 'Advanced'),
)


class UserManager(UserManager):
    def search(self, query=None):
        qs = self.get_queryset()
        if query is not None:
            or_lookup = (Q(username__icontains=query) |
                         Q(first_name__icontains=query)|
                         Q(last_name__icontains=query)|
                         Q(email__icontains=query)
                        )
            qs = qs.filter(or_lookup).distinct() # distinct() is often necessary with Q lookups
        return qs


class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_lecturer = models.BooleanField(default=False)
    is_parent = models.BooleanField(default=False)
    is_dep_head = models.BooleanField(default=False)
    phone = models.CharField(max_length=60, blank=True, null=True)
    nationality = models.CharField(max_length=60, blank=True, null=True)
    address = models.CharField(max_length=60, blank=True, null=True)
    picture = models.ImageField(upload_to='profile_pictures/%y/%m/%d/', default='default.png', null=True)
    email = models.EmailField(blank=True, null=True)
    state_of_origin = models.CharField(max_length=100, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    weight = models.IntegerField(blank=True, null=True)
    height = models.IntegerField(blank=True, null=True)
    meal_allergic_comment = models.TextField(blank=True, null=True)
    medical_record = models.FileField(upload_to='medical_records/', blank=True, null=True)
    computer_labs = models.CharField(max_length=10, choices=CHOICES, default='not_now')
    library_services = models.CharField(max_length=10, choices=CHOICES, default='not_now')
    counseling = models.CharField(max_length=10, choices=CHOICES, default='not_now')
    student_housing = models.CharField(max_length=10, choices=CHOICES, default='not_now')
    financial_aid = models.CharField(max_length=10, choices=CHOICES, default='not_now')
    cafeteria_services = models.CharField(max_length=10, choices=CHOICES, default='not_now')
    mental_health_services = models.CharField(max_length=10, choices=CHOICES, default='not_now')
    tutoring_centers = models.CharField(max_length=10, choices=CHOICES, default='not_now')
    technology_support = models.CharField(max_length=10, choices=CHOICES, default='not_now')
    disability_services = models.CharField(max_length=10, choices=CHOICES, default='not_now')
    international_student_services = models.CharField(max_length=10, choices=CHOICES, default='not_now')
    laboratory_facilities = models.CharField(max_length=10, choices=CHOICES, default='not_now')
    academic_advising = models.CharField(max_length=10, choices=CHOICES, default='not_now')
    bus_service = models.CharField(max_length=10, choices=BUS_SERVICE_CHOICES, default='not_now')
    bus_service_type = models.CharField(max_length=10, choices=BUS_SERVICE_TYPE_CHOICES, blank=True, null=True,default='not_now')
    pickup_or_dropoff = models.CharField(max_length=10, choices=PICKUP_OR_DROPOFF_CHOICES, blank=True, null=True,default='not_now')
    username_validator = ASCIIUsernameValidator()

    objects = UserManager()

    @property
    def get_full_name(self):
        full_name = self.username
        if self.first_name and self.last_name:
            full_name = self.first_name + " " + self.last_name
        return full_name

    def __str__(self):
        return '{} ({})'.format(self.username, self.get_full_name)

    @property
    def get_user_role(self):
        if self.is_superuser:
            return "Admin"
        elif self.is_student:
            return "Student"
        elif self.is_lecturer:
            return "Lecturer"
        elif self.is_parent:
            return "Parent"

    def get_picture(self):
        try:
            return self.picture.url
        except:
            no_picture = settings.MEDIA_URL + 'default.png'
            return no_picture

    def get_absolute_url(self):
        return reverse('profile_single', kwargs={'id': self.id})

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        try:
            img = Image.open(self.picture.path)
            if img.height > 300 or img.width > 300:
                output_size = (300, 300)
                img.thumbnail(output_size)
                img.save(self.picture.path)
        except:
            pass

    def delete(self, *args, **kwargs):
        if self.picture.url != settings.MEDIA_URL + 'default.png':
            self.picture.delete()
        super().delete(*args, **kwargs)

class StudentManager(models.Manager):
    def search(self, query=None):
        qs = self.get_queryset()
        if query is not None:
            or_lookup = (Q(level__icontains=query) |
                         Q(department__icontains=query) |
                         Q(session__icontains=query))
            qs = qs.filter(or_lookup).distinct()
        return qs


class Student(models.Model):
    student = models.OneToOneField(User, on_delete=models.CASCADE, default='')
    Admission_id = models.CharField(max_length=20,  blank=True,default='')
    level = models.CharField(max_length=25, choices=LEVEL, default='')
    term = models.CharField(max_length=25, choices=SEMESTER,default='')
    session = models.CharField(max_length=25, choices=YEARS,default='')
    department = models.ForeignKey(Program, on_delete=models.CASCADE, null=True)
    payment = models.CharField(max_length=25, choices=PAYMENT_CHOICES, blank=True,null=True,default='')

    objects = StudentManager()

    def __str__(self):
        return f"{self.student}"

    def get_absolute_url(self):
        return reverse('profile_single', kwargs={'id': self.id})

    def delete(self, *args, **kwargs):
        self.student.delete()
        super().delete(*args, **kwargs)

    def generate_unique_admission_number(self):
        while True:
            random_number = random.randint(10000, 99999)
            current_year = datetime.now().year
            admission_number = f"HIGS/{random_number}/{current_year}"
            if not Student.objects.filter(Admission_id=admission_number).exists():
                return admission_number

    def save(self, *args, **kwargs):
        if not self.Admission_id:
            self.Admission_id = self.generate_unique_admission_number()
        super().save(*args, **kwargs)


class Message(models.Model):
    title = models.CharField(max_length=255, blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    students = models.ForeignKey(Student, on_delete=models.CASCADE, blank=True, null=True)
    level = models.CharField(max_length=25, choices=LEVEL, default='', blank=True, null=True)
    year = models.CharField(max_length=25, choices=YEARS, default='', blank=True, null=True)
    department = models.ForeignKey(Program, on_delete=models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    is_read = models.BooleanField(default=False)


    @classmethod
    def unread_count(cls, Student, LEVEL, YEARS, program ):
        return cls.objects.filter(students=Student, level=LEVEL, year=YEARS, department=program, is_read=False).count()

    def __str__(self):
        return f"{self.title} read by {self.students} is {self.is_read}"


class Parent(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=120)
    last_name = models.CharField(max_length=120)
    occupation = models.CharField(max_length=60, blank=True, null=True)
    alt_phone = models.CharField(max_length=60, blank=True, null=True)
    relation_ship = models.CharField(max_length=60, blank=True, null=True)
    email_p = models.EmailField(blank=True, null=True)

    def __str__(self):
        return f"{self.user.username}'s {self.__class__.__name__}"

class DepartmentHead(models.Model):

templates/accounts/add_staff.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div id="input-nav"><a href="{% url 'home' %}" class="primary1">Home</a> <i>&rsaquo;</i> 
    <a href="{% url 'lecturer_list' %}" class="primary1">Teacher</a> <i>&rsaquo;</i> Add</div>
<br>
<div class="title-1"><i class="fas fa-chalkboard-teacher"></i>Teacher Add Form</div>
<div class="title-line"></div><br>


<form action="" method="POST">{% csrf_token %}
    <div class="row mb-3">
        <div class="col-md-6">
            <div class="card">
                <p class="form-title">Login Info</p>
                <div class="p-2">
                    <div class="form-group">
                        <b>ID No.</b>{{ form.username }}
                        <span class="danger">{{ form.username.errors }}</span>
                        <p class="text-muted-xs">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</p>
                    </div>
                    <div class="form-group">
                        <b>{{ form.password1.label }}</b>{{ form.password1 }}
                        <span class="danger">{{ form.password1.errors }}</span>
                        <p class="text-muted-xs">
                            The password can't be too similar to other personal information.<br>
                            The password must contain at least 8 characters.<br>
                            The password can't be a commonly used password.<br>
                            The password can't be entirely numeric.
                        </p>
                    </div>
                    <div class="form-group">
                        <b>{{ form.password2.label }}</b>{{ form.password2 }}
                        <span class="danger">{{ form.password2.errors }}</span>
                        <p class="text-muted-xs">Enter the same password as before, for verification.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <p class="form-title">Personal Info</p>
                <div class="p-2">
                    <div class="form-group">
                        <b>{{ form.first_name.label }}</b>{{ form.first_name }}
                        <span class="danger">{{ form.first_name.errors }}</span>
                    </div>
                    <div class="form-group">
                        <b>{{ form.last_name.label }}</b>{{ form.last_name }}
                        <span class="danger">{{ form.last_name.errors }}</span>
                    </div>
                    <div class="form-group">
                        <b>{{ form.email.label }}</b>{{ form.email }}
                        <span class="danger">{{ form.email.errors }}</span>
                    </div>
                    <div class="form-group">
                        <b>{{ form.address.label }}</b>{{ form.address }}
                        <span class="danger">{{ form.address.errors }}</span>
                    </div>
                    <div class="form-group">
                        <b>{{ form.phone.label }}</b>{{ form.phone }}
                        <span class="danger">{{ form.phone.errors }}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <center><input class="btn btn-outline-primary" type="submit" value="Save"></center>
</form>

{% endblock content %}

templates/accounts/base.html
{% extends "base.html" %}

templates/accounts/email_confirm.html
{% extends "base.html" %}

{% load i18n %}
{% load account %}

{% block head_title %}{% trans "Confirm E-mail Address" %}{% endblock %}


{% block content %}
{% load static %}
<link href="{% static 'css/musicweb.css' %}" rel="stylesheet">


<h1>{% trans "Confirm E-mail Address" %}</h1>

{% if confirmation %}

{% user_display confirmation.email_address.user as user_display %}

<p>{% blocktrans with confirmation.email_address.email as email %}Please confirm that <a href="mailto:{{ email }}">{{ email }}</a> is an e-mail address for user {{ user_display }}.{% endblocktrans %}</p>

<form method="post" action="{% url 'account_confirm_email' confirmation.key %}">
{% csrf_token %}
    <button type="submit">{% trans 'Confirm' %}</button>
</form>

{% else %}

{% url 'account_email' as email_url %}

<p>{% blocktrans %}This e-mail confirmation link expired or is invalid. Please <a href="{{ email_url }}">issue a new e-mail confirmation request</a>.{% endblocktrans %}</p>

{% endif %}

{% endblock %}

templates/accounts/logout.html
{% extends "base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Sign Out" %}{% endblock %}

{% block content %}
{% load static %}
<body>
<link href="{% static 'css/musicweb.css' %}" rel="stylesheet">

<div class="row justify-content-center">
  <div class="col-md-6 col-sm-12 text-center pb-3">
    <h1>{% trans "Sign Out" %}</h1>
    <p>{% trans 'Are you sure you want to sign out?' %}</p>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-md-6 col-sm-12">
    <form method="post" action="{% url 'account_logout' %}">
      {% csrf_token %}
      {% if redirect_field_value %}
      <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
      {% endif %}
      <div class="d-grid gap-2">
      <button class="btn btn-dark" type="submit">{% trans 'Sign Out' %}</button>
      </div>
    </form>
  </div>
</div>
</body>

{% endblock %}

templates/accounts/message_form.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div id="input-nav">
    <a href="{% url 'home' %}" class="primary1">Home</a> <i>&rsaquo;</i>
    <a href="{% url 'admin_panel' %}" class="primary1">Admin Panel</a> <i>&rsaquo;</i> Send Note Message
</div>

<div class="title-1">Send Note Message</div>
<div class="title-line"></div>


</div>
    <div class="table-responsive table-striped m-0 mt-2" style="width: 80%;">
        <table class="table">
            <tbody>
                <tr>
            <form class="search-form" action="" method="GET">
                <div class="search-container">
                    <input  class="au-input" type="text" id="search" name="q" placeholder="SEARCH ENGINE.... #phone, #Email, #username, " value="{{ request.GET.q }}" />
                    <button class="btn2" type="submit">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </form>

                </tr>
            </tbody>
        </table>
    </div>


<form method="GET">
    <div class="table-responsive table-shadow table-light table-striped m-0 mt-2">
        <table class="table">
            <thead>
                <tr>
                    <th>Filter By:</th>
                    <th><span for="{{ filter_form.level.id_for_label }}"><strong>Level:</strong></span>{{ filter_form.level }}</th>
                    <th><span for="{{ filter_form.session.id_for_label }}"><strong>Session:</strong></span>{{ filter_form.session }}</th>
                    <th><span for="{{ filter_form.payment.id_for_label }}"><strong>Payment:</strong></span>{{ filter_form.payment }}</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                </tr>
            </tbody>
        </table>
    <button class="btn btn-primary" type="submit">Apply Filters</button>

    </div>

</form>
<form method="POST">
    {% csrf_token %}
    <div class="table-responsive table-shadow table-light table-striped m-0 mt-2">
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th><label for="select-all">Mark All</label> <input type="checkbox" id="select-all" /></th>
                    <th style="color: navy"> PAYMENT STATUS </th>
                    <th>Class</th>
                    <th> Full Name </th>
                    <th> Phone Number </th>
                    <th> Email </th>
                    <th> Admission No. </th>
                </tr>
            </thead>
            <tbody>
                {% for student in students %}
                <tr>
                    <td>{{ forloop.counter }}.</td>
                    <td scope="row">
                        <input type="checkbox" name="selected_students" value="{{ student.id }}">
                    </td>
                    <td>{{ student.payment }}</td>

                    <td>{{ student.level }} {{ student.session }}</td>
                    <td><a href="{% url 'profile_single' student.student.id %}">{{ student.student.get_full_name }}</a></td>
                    <td>{{ student.student.phone }}</td>
                    <td>{{ student.student.email }}</td>
                    <td>{{ student.Admission_id }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="7" class="text-center">
                        <span class="text-danger">
                            <i class="far fa-frown"></i> No Student.
                            {% if request.user.is_superuser %}
                            <a href="{% url 'add_student' %}">
                                <i class="primary" style="font-size: 22px;">Add Student Now.</i>
                            </a>
                            {% endif %}
                        </span>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="pagination">
    <span class="step-links">
        {% if students.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ students.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current-page">
            Page {{ students.number }} of {{ students.paginator.num_pages }}.
        </span>

        {% if students.has_next %}
            <a href="?page={{ students.next_page_number }}">next</a>
            <a href="?page={{ students.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
    </div>
    <div class="row justify-content-center mt-3 mb-5">
        <div class="border-bottom">
            <label for="id_title">Title:</label>
            {{ form.title }}
            {% if form.title.errors %}
                <div class="text-danger">
                    {% for error in form.title.errors %}
                        {{ error }}
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
    <div class="row justify-content-center mt-0 mb-2">
        <div class=" border-bottom">
            <label for="id_content">Content:</label>
            {{ form.content }}
            {% if form.content.errors %}
                <div class="text-danger">
                    {% for error in form.content.errors %}
                        {{ error }}
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
    <div class="row justify-content-center mt-0 mb-2">
        <div class="border-bottom">
     <button class="btn btn-success mt-0" type="submit">Send Message to Selected Students!</button>
        </div>
    </div>
</form>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Get the "Mark All" checkbox and all student checkboxes
        var markAllCheckbox = document.getElementById('select-all');
        var studentCheckboxes = document.querySelectorAll('input[type="checkbox"][name="selected_students"]');

        // Add event listener to the "Mark All" checkbox
        markAllCheckbox.addEventListener('change', function() {
            // Iterate over all student checkboxes and set their checked property
            studentCheckboxes.forEach(function(checkbox) {
                checkbox.checked = markAllCheckbox.checked;
            });
        });
    });
</script>

<style>
.search-container {
    position: relative;
}

.au-input {
    padding-right: 40px;
}
.btn2 {
    position: absolute;
    top: 0;
    right: 0;
    height: 100%;
    padding: 5px 5px;
    background-color: transparent;
    border: none;
    cursor: pointer;
}

.btn2 i {
    margin-right: 5px;
}

    .form-block {
    margin-bottom: 10px;
}

label {
    display: flex;
    font-weight: bold;
    margin-bottom: 5px;
    border: none;
}
.au-input {
    width: 100%;
    border: 2px solid navy;
    border-radius: 20px;
}
</style>

{% endblock content %}

templates/accounts/parent_form.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div id="input-nav"><a style="color: orange;" href="{% url 'home' %}" class="primary1">Home</a>
	|<strike style="color: blue;"href="" class="primary1">FORM 1/3</strike>
	|<strike style="color: blue;" class="primary1"> FORM 2/3</strike>
	|<a style="color: gray;" class="primary1">FORM 3/3</a>
</div>

<p class="title-1"><i class="fas fa-book"></i>STAGE 3/3 | <strong>Parent's Data </strong></p>

	  <div class="row">
		  <div class="col-lg-6">
		  <div class="blue-gradient text-light p-3 mb-2">
			  <h1 class="lead my-0">
				<i class="fas fa-work mr-2"></i>Update Parent's Data
			  </h1>
		  </div>

<form method="POST" action="{% url 'add_parent' %}" class="parent-form">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_first_name">Parent's First Name:</label>
        <input type="text" name="first_name" id="id_first_name" class="form-control" placeholder="Enter First Name" required>
    </div>
    <div class="form-group">
        <label for="id_last_name">Parent's Last Name:</label>
        <input type="text" name="last_name" id="id_last_name" class="form-control" placeholder="Enter Last Name" required>
    </div>
    <div class="form-group">
        <label for="id_occupation">Parent's Occupation:</label>
        <input type="text" name="occupation" id="id_occupation" class="form-control" placeholder="Enter Occupation" required>
    </div>
    <div class="form-group">
        <label for="id_alt_phone">Parent's Other Phone Line:</label>
        <input type="text" name="alt_phone" id="id_alt_phone" class="form-control" placeholder="Enter Other Phone Line" required>
    </div>

    <!-- Hidden email field -->
    <input type="hidden" name="email_p" value="{{ user.email }}" readonly>

    <div class="form-group">
        <label for="id_relation_ship">Select Relationship:</label>
                  <select name="relation_ship" id="id_relation_ship" required>
            {% for option_value, option_label in relationship_options %}
              <option value="{{ option_value }}">{{ option_label }}</option>
            {% endfor %}
          </select>
    </div>
        <button class="button" type="submit"  style="margin-top:10;">COMPLETED</button>
</form>
          </div>
      </div>
{% endblock %}

templates/accounts/password_change.html
{% extends "base.html" %}

{% load i18n %}

{% load crispy_forms_tags %}

{% block head_title %}{% trans "Change Password" %}{% endblock %}

{% block content %}
{% load static %}
<link href="{% static 'css/musicweb.css' %}" rel="stylesheet">

    <div class="row">
        <div class="col-md-6 col-sm-12">
            <h1>{% trans "Change Password" %}</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 col-sm-12">
            <form method="POST" action="{% url 'account_change_password' %}" class="login">
                {% csrf_token %}
                {{ form }}
                <button class="btn btn-dark btn-block" type="submit" name="action">{% trans "Change Password" %}</button>
            </form>
        </div>
    </div>

{% endblock %}